add ProfilePage, add Button, add classNames
OsmanAlb/Ed-project pull request #14
Opened 2023-12-30 18:39 UTC by EduardDE7

2023-12-30 18:56 UTC, OsmanAlb commented on src/pages/ProfilePage.jsx
> +      </div>
To add change image.)

2023-12-30 18:57 UTC, OsmanAlb commented on src/pages/ProfilePage.jsx
What do you think

2023-12-30 19:02 UTC, OsmanAlb requested changes
Change the name

2023-12-30 19:08 UTC, EduardDE7 commented
will be done

2023-12-30 19:41 UTC, merged

2024-01-02 13:21 UTC, OsmanAlb reviewed
all good