add input resolve #28
OsmanAlb/Ed-project pull request #38
Opened 2024-01-06 11:10 UTC by annymal

add input

2024-01-06 19:07 UTC, OsmanAlb approved these changes

2024-01-07 05:34 UTC, EduardDE7 requested changes

2024-01-07 05:34 UTC, EduardDE7 commented on client/src/components/ui/Input.jsx
> +	if (link) {
зачем тут линк?

2024-01-09 16:32 UTC, EduardDE7 approved these changes

2024-01-09 16:34 UTC, merged